version: '3.9'

services:

  api:
    container_name: panel-module-app-api
    build: . #build Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app/panel-module-app # the volume mirrors the sources into the container so it catches development changes
    environment:
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database

  database:
    container_name: postgres-db
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
